const raidName = "Manaforge Omega";

const tierSlotDict = {
    "Helm":"Foreboding Beaker",
    "Head":"Foreboding Beaker",
    1:"Foreboding Beaker",
    "Shoulder":"Yearning Cursemark",
    "Shoulders":"Yearning Cursemark",
    3:"Yearning Cursemark",
    "Chest":"Voidglass Contaminant", 
    20:"Voidglass Contaminant",
    5:"Voidglass Contaminant",
    "Legs":"Silken Offering",
    7:"Silken Offering",
    "Gloves":"Binding Agent",
    "Hands":"Binding Agent",
    "Hand":"Binding Agent",
    10:"Binding Agent"
};

const classTierDict = {
    "death-knight": "Hollow Sentinel",
    "demon-hunter": "Charhound's Vicious",
    "druid": "Mother Eagle",
    "evoker": "Spellweaver's Immaculate",
    "hunter": "Midnight Herald",
    "mage": "Augur's Ephemeral",
    "monk": "Fallen Storms",
    "paladin": "Lucent Battalion",
    "priest": "Dying Star",
    "rogue": "Sudden Eclipse",
    "shaman": "Channeled Fury",
    "warlock": "Inquisitor's",
    "warrior": "Living Weapon"
};

const itemBossDict = { "Mounted Manacannons":"Plexus Sentinel",
"Singed Sievecuffs":"Plexus Sentinel",
"Irradiated Impurity Filter":"Plexus Sentinel",
"Atomic Phasebelt":"Plexus Sentinel",
"Chambersieve Waistcoat":"Plexus Sentinel",
"Arcanotech Wrist-Matrix":"Plexus Sentinel",
"Manaforged Displacement Chassis":"Plexus Sentinel",
"Sterilized Expulsion Boots":"Plexus Sentinel",
"Logic Gate: Alpha":"Plexus Sentinel",
"Overclocked Plexhammer":"Plexus Sentinel",
"Factory-Issue Plexhammer":"Plexus Sentinel",
"Obliteration Beamglaive":"Plexus Sentinel",
"Eradicating Arcanocore":"Plexus Sentinel",
"Laced Lair-Steppers":"Loom'ithar",
"Deathbound Shoulderpads":"Loom'ithar",
"Colossal Lifetether":"Loom'ithar",
"Discarded Nutrient Shackles":"Loom'ithar",
"Prodigious Gene Splicer":"Loom'ithar",
"Piercing Strandbow":"Loom'ithar",
"Ward of the Weaving-Beast":"Loom'ithar",
"Astral Antenna":"Loom'ithar",
"Loom'ithar's Living Silk":"Loom'ithar",
"Dreadful Silken Offering":"Loom'ithar",
"Mystic Silken Offering":"Loom'ithar",
"Venerated Silken Offering":"Loom'ithar",
"Zenith Silken Offering":"Loom'ithar",
"Frock of Spirit's Reunion":"Soulbinder Naazindhri",
"Bindings of Lost Essence":"Soulbinder Naazindhri",
"Deathspindle Talons":"Soulbinder Naazindhri",
"Fresh Ethereal Fetters":"Soulbinder Naazindhri",
"Chrysalis of Sundered Souls":"Soulbinder Naazindhri",
"Unbound Training Claws":"Soulbinder Naazindhri",
"Voidglass Spire":"Soulbinder Naazindhri",
"Soulbinder's Embrace":"Soulbinder Naazindhri",
"Naazindhri's Mystic Lash":"Soulbinder Naazindhri",
"Dreadful Binding Agent":"Soulbinder Naazindhri",
"Mystic Binding Agent":"Soulbinder Naazindhri",
"Venerated Binding Agent":"Soulbinder Naazindhri",
"Zenith Binding Agent":"Soulbinder Naazindhri",
"Forgeweaver's Journal Holster":"Forgeweaver Araz",
"Laboratory Test Slippers":"Forgeweaver Araz",
"Harvested Attendant's Uniform":"Forgeweaver Araz",
"Breached Containment Guards":"Forgeweaver Araz",
"Logic Gate: Omega":"Forgeweaver Araz",
"Marvel of Technomancy":"Forgeweaver Araz",
"Photon Sabre Prime":"Forgeweaver Araz",
"Iris of the Dark Beyond":"Forgeweaver Araz",
"Araz's Ritual Forge":"Forgeweaver Araz",
"Dreadful Foreboding Beaker":"Forgeweaver Araz",
"Mystic Foreboding Beaker":"Forgeweaver Araz",
"Venerated Foreboding Beaker":"Forgeweaver Araz",
"Zenith Foreboding Beaker":"Forgeweaver Araz",
"Bloodwrath's Gnarled Claws":"The Soul Hunters",
"Interloper's Silken Striders":"The Soul Hunters",
"Darksorrow's Corrupted Carapace":"The Soul Hunters",
"Interloper's Reinforced Sandals":"The Soul Hunters",
"Clasp of Furious Freedom":"The Soul Hunters",
"Interloper's Chain Boots":"The Soul Hunters",
"Yoke of Enveloping Hatred":"The Soul Hunters",
"Interloper's Plated Sabatons":"The Soul Hunters",
"Collapsing Phaseblades":"The Soul Hunters",
"Event Horizon":"The Soul Hunters",
"Sigil of the Cosmic Hunt":"The Soul Hunters",
"Brand of Ceaseless Ire":"The Soul Hunters",
"Dreadful Yearning Cursemark":"The Soul Hunters",
"Mystic Yearning Cursemark":"The Soul Hunters",
"Venerated Yearning Cursemark":"The Soul Hunters",
"Zenith Yearning Cursemark":"The Soul Hunters",
"Conjoined Glass Bracers":"Fractillus",
"Kinetic Dunerunners":"Fractillus",
"Bite of the Astral Wastes":"Fractillus",
"Shrapnel-Fused Legguards":"Fractillus",
"Voidglass Kris":"Fractillus",
"Lacerated Current Caster":"Fractillus",
"Fractillus' Last Breath":"Fractillus",
"Diamantine Voidcore":"Fractillus",
"Unyielding Netherprism":"Fractillus",
"Dreadful Voidglass Contaminant":"Fractillus",
"Mystic Voidglass Contaminant":"Fractillus",
"Venerated Voidglass Contaminant":"Fractillus",
"Zenith Voidglass Contaminant":"Fractillus",
"Sandals of Scarred Servitude":"Nexus-King Salhadaar",
"Twilight Tyrant's Veil":"Nexus-King Salhadaar",
"Reaper's Dreadbelt":"Nexus-King Salhadaar",
"Elite Shadowguard Legwraps":"Nexus-King Salhadaar",
"Pactbound Vambraces":"Nexus-King Salhadaar",
"Royal Voidscale Gauntlets":"Nexus-King Salhadaar",
"Darkrider Sabatons":"Nexus-King Salhadaar",
"Beacons of False Righteousness":"Nexus-King Salhadaar",
"Salhadaar's Folly":"Nexus-King Salhadaar",
"Vengeful Netherspike":"Nexus-King Salhadaar",
"Voidglass Sovereign's Blade":"Nexus-King Salhadaar",
"Oath-Breaker's Recompense":"Nexus-King Salhadaar",
"Maw of the Void":"Nexus-King Salhadaar",
"Perfidious Projector":"Nexus-King Salhadaar",
"Nexus-King's Command":"Nexus-King Salhadaar",
"Singularity Cincture":"Dimensius, the All-Devouring",
"Stellar Navigation Slacks":"Dimensius, the All-Devouring",
"Time-Compressed Wristguards":"Dimensius, the All-Devouring",
"Winged Gamma Handlers":"Dimensius, the All-Devouring",
"Claws of Failed Resistance":"Dimensius, the All-Devouring",
"Greaves of Shattered Space":"Dimensius, the All-Devouring",
"Artoshion's Abyssal Stare":"Dimensius, the All-Devouring",
"Ultradense Fission Girdle":"Dimensius, the All-Devouring",
"Band of the Shattered Soul":"Dimensius, the All-Devouring",
"Ergospheric Cudgel":"Dimensius, the All-Devouring",
"Supermassive Starcrusher":"Dimensius, the All-Devouring",
"All-Devouring Nucleus":"Dimensius, the All-Devouring",
"Screams of a Forgotten Sky":"Dimensius, the All-Devouring",
"Hungering Void Curio":"Dimensius, the All-Devouring"
};

const bossOrder = ["Plexus Sentinel","Loom'ithar","Soulbinder Naazindhri","Forgeweaver Araz","The Soul Hunters","Fractillus","Nexus-King Salhadaar","Dimensius, the All-Devouring"];

const tierTokenDict = {
    "death-knight":"Dreadful",
    "demon-hunter":"Dreadful",
    "druid":"Mystic",
    "evoker":"Zenith",
    "hunter":"Mystic",
    "mage":"Mystic",
    "monk":"Zenith",
    "paladin":"Venerated",
    "priest":"Venerated",
    "rogue":"Zenith",
    "shaman":"Venerated",
    "warlock":"Dreadful",
    "warrior":"Zenith"
};

const wowClassDict = {
    "death-knight": {
        frost: "dps",
        blood: "tank",
        unholy: "dps",
    },
    "demon-hunter": {
        vengeance: "tank",
        havoc: "dps",
    },
    "druid": {
        balance: "dps",
        guardian: "tank",
        feral: "dps",
        restoration: "healing",
    },
    "evoker": {
        augmentation: "dps",
        preservation: "healing",
        devastation: "dps",
    },
    "hunter": {
        "beast-mastery": "dps",
        survival: "dps",
        marksmanship: "dps",
    },
    "mage": {
        frost: "dps",
        fire: "dps",
        arcane: "dps",
    },
    "monk": {
        brewmaster: "tank",
        mistweaver: "healing",
        windwalker: "dps",
    },
    "paladin": {
        retribution: "dps",
        protection: "tank",
        holy: "healing",
    },
    "priest": {
        shadow: "dps",
        holy: "healing",
        discipline: "healing",
    },
    "rogue": {
        outlaw: "dps",
        assassination: "dps",
        subtlety: "dps",
    },
    "shaman": {
        restoration: "healing",
        elemental: "dps",
        enhancement: "dps",
    },
    "warlock": {
        affliction: "dps",
        destruction: "dps",
        demonology: "dps",
    },
    "warrior": {
        arms: "dps",
        fury: "dps",
        protection: "tank",
    },
};